service: CoduraWiseFront

frameworkVersion: "3"

plugins:
  - serverless-finch

# -----------------------------------------------------------------------------
custom:
  stage: ${opt:stage, 'dev'}
  coduranceHostedZoneId: Z2P3IWUGUFUUGE
  coduranceHostedZoneName: codurance.io
  frontDomain:
    dev: codurawise-dev.codurance.io
    prod: codurawise-prod.codurance.io
  client:
    bucketName: "${self:custom.frontDomain.${opt:stage, 'dev'}}"
    distributionFolder: ../../frontend/build

# -----------------------------------------------------------------------------
provider:
  name: aws
  runtime: java11
  profile: codurawise
  region: eu-west-3

  stage: ${self:custom.stage}

# -----------------------------------------------------------------------------
# resources:
#   Resources:
#     DnsRecord:
#       Type: "AWS::Route53::RecordSet"
#       Properties:
#         AliasTarget:
#           DNSName: s3-website.${self:provider.region}.amazonaws.com
#           HostedZoneId: ${self:custom.coduranceHostedZoneId}
#         HostedZoneName: ${self:custom.coduranceHostedZoneName}.
#         Name: ${self:custom.frontDomain.${opt:stage, 'dev'}}
#         Type: 'A'