name: CI for development branch

on: workflow_dispatch

jobs:
  deploy-all:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build and Test with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test
        build-root-directory: ./backend

    - name: Create fat package (include all dependencies) with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: packageFat
        build-root-directory: ./backend
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install packages
      working-directory: ./frontend
      run: npm install
    
    - name: Test frontend
      working-directory: ./frontend
      run: npm run test
    
    - name: Build the frontend
      working-directory: ./frontend
      run: npm run build
        
        
        
        
