name: CI for development branch

on: workflow_dispatch

jobs:
  deploy-back-end:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
