name: Frontend build and deploy

on: 
  workflow_dispatch:

jobs:
  deploy-front-end:
  
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend
        
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
