name: Frontend build and deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - development
    paths:
      - 'frontend/*'
      - 'infra/*'

jobs:
  build-and-test:
  
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend
        
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install packages
      run: npm install
    
    - name: Test frontend
      run: npm run test
    
    - name: Build the frontend
      run: npm run build
    - name: Upload front-end build folder for deploy job
      uses: actions/upload-artifact@v3
      with:
        name: front-end-build
        path: frontend/build/
   
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: infra
        
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
         
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
    - name: Create env file
      run: | # cp sample.env.yml env.yml
        cat > env.yml << EOF
        ${{ secrets.ENV }}
        EOF
    - name: Install NPM dependencies
      run: npm install
    - name: Download front-end-build for deploy
      uses: actions/download-artifact@v3
      with:
        name: front-end-build
    - name: Move
      run: |
        echo "List . -------"
        ls .
        echo "List .. -------"
        ls ..
        pwd
    - name: Deploy Front-end to S3 bucket
      run: sls client deploy -s dev --no-confirm
